### ISSUE TITLE
Should Date, Time and DateTime constructors take unsigned integers instead of signed?

### ISSUE THREAD

**Issue by twistedfall** [BurntSushi/jiff#102]
Hi, thank you a lot for your work!

While trying to transition one of my smaller crates from `chrono` to `jiff` I stumbled upon the fact that the `Date`, `Time` and `DateTime` constructors take signed integers which doesn't make too much sense IMO (beside year) as negative values will be rejected by the validation anyway. `chrono` crate takes unsigned integers in that case. What is the reasoning behind this?

**Comment by BurntSushi** [comment]
I think this is a duplicate of #35.

**Comment by twistedfall** [comment]
Yes, it's the same question, sorry for not finding it earlier!

I understand the reasoning, thanks. Just to express my personal opinion: I try to limit the the range of the types exposed via public APIs as fully as possible (probably as far as creating an enum for `Month` in this case, this also takes care of 0/1 based months) so my preference would be to accept unsigned types for days, hours, etc and do range checks and type conversion inside those constructors. I can work on a PR if you think it's something worth including.

**Comment by BurntSushi** [comment]
As I mentioned in #35, both `i8` and `u8` have precisely the same number of illegal values. So using `u8` doesn't actually limit the range at all. It just shifts it around. Interestingly, Chrono uses a `u32` for day values, which has _a lot_ more illegal values than Jiff's `i8`.

I had considered using a `Month` enum, but I considered it a bit too weird. It's also a lot more verbose. In my experience, using 1-based offsets for months is fine because it's what every expects. There are some APIs around (that I personally consider legacy) like a [POSIX `tm` struct](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/time.h.html) which requires the month be a zero based offset, but AFAIK, this is universally hated and confusing.

In any case, if you feel strongly about the `Month` enum, I'd recommend opening a new issue and discussing the points for and against. Code samples would help too. I suspect I'll be pretty firmly against it unless the current paradigm ends up causing folks issues. But when I was doing my research for datetime libraries, "month represented as an integer starting at `1`" did not come up _at all_ as a footgun. Moreover, Temporal uses the same representation, an integer month, and doesn't allow the full spelling of the month as far as I know. (Although they might have different reasons, since they're generally a bit more careful about internationalization than Jiff is. And Jiff is already using the English names for weekday in the `jiff::civil::Weekday` enum.)

This is in contrast to `Weekday` where the weeks can start on Sunday or Monday, _and_ the offset doesn't have a strong connection to being zero based or one based, as in the case of month. So using an enum there ends up conferring a bigger benefit.

As far as using unsigned types here... I don't see myself changing them on opinion alone. I want to see real examples showing why the signed types are inconvenient or problematic and why the unsigned version would solve the problem.

**Comment by twistedfall** [comment]
Thank you for the extensive explanation! I don't have a really strong opinion here too, so let's close this :)
