### ISSUE TITLE
Remove `Sub` implementation for `Span` to `Timestamp`

### ISSUE THREAD

**Issue by ClementNerma** [BurntSushi/jiff#145]
I stumbled across a little problem today. I wrote the following code:

```rust
let period = match period {
    PopularityPeriod::Daily => Span::new(),
    PopularityPeriod::Weekly => Span::new().weeks(1),
    PopularityPeriod::Monthly => Span::new().months(1),
    PopularityPeriod::Yearly => Span::new().years(1),
};

let start_period = Timestamp::now() - period;
```

And at runtime my code panicked with the following: `subtracting span from timestamp overflowed: Error { inner: ErrorInner { kind: Adhoc(operation can only be performed with units of hours or smaller, but found non-zero week units), cause: None } }`.

I find this very confusing because I don't expect add and subtract operations to be fallible (unless you have an _actual_ overflow or underflow).

Also it's not obvious from the error message _why_ substraction is limited to units of hours or smaller, instead of allowing days, weeks, months and even years.

I really think the `Sub` implementation, despite being convenient, should be removed for `Span` on `Timestamp` as I believe it to be very misleading and error-prone.

**EDIT:** Just like `Zoned` doesn't support substracting `Span` but forces to use `.checked_sub()` instead. And obviously the same goes for additions as well.

What do you think?

**Comment by BurntSushi** [comment]
> Also it's not obvious from the error message why substraction is limited to units of hours or smaller, instead of allowing days, weeks, months and even years.

Yeah it's somewhat hinted at here: https://docs.rs/jiff/latest/jiff/struct.Timestamp.html#method.checked_add

But basically, since a `Timestamp` has no way of resolving the length of a day, the API is preventing you from a footgun. The logic here is basically this:

* A panic on an arithmetic op is better than a silently incorrect answer. Especially when _most_ of the time, the answer might actually be correct.
* The presence of the arithmetic op is convenient enough to justify its presence. And since `std` has already established precedent that arithmetic ops are _fallible_, making Jiff's arithmetic ops fallible is "generally okay."

I do agree that there is a slight difference here in that fallibility is not just due to overflow, but due to the units themselves. I'm not sure if this on its own is really worth removing the trait implementation here. Especially since it seems like overflow is way worse of a problem in that it only happens at the extremes, where as the error you hit will _always_ occur when units greater than hours are used. So it's a more visible speed bump.

Perhaps we can instead improve the docs and the error message. I think improving the error message is not that bad, although _explaining_ why units of days or greater inside the error is probably quite difficult. Perhaps the error can suggest using `Zoned` instead. And the problem with improving the docs is really, where do you put it? If it were in a new section on `Timestamp`, would you have seen it?

> **EDIT:** Just like `Zoned` doesn't support substracting `Span` but forces to use `.checked_sub()` instead. And obviously the same goes for additions as well.

`Zoned` definitely supports it, but since `Zoned` isn't `Copy`, arithmetic is done via borrow. It's explained in the docs for `Zoned`: https://docs.rs/jiff/latest/jiff/struct.Zoned.html#arithmetic

**Comment by ClementNerma** [comment]
Thanks for your explanations !

The problem I see with this behaviour is that you may have runtime problems you didn't even know could happen.

For std ops I didn't know they could be fallible like that, thanks for pointing it out. That means I also disagree with how rust explains these but that's an entirely different subject then ^^"

But here what bothers me is that the operation doesn't fail because of an overflow / underflow or something else like this, but because it allows operations that may make no sense at all. I don't know if I'm clear?

Anyway if I'm the only one bothered by this behaviour of course it'll stay as it is. Thanks for explaining all this anyway :)

**Comment by BurntSushi** [comment]
Yes, it's all a trade off. I would strongly encourage you to read [RFC 0560](https://rust-lang.github.io/rfcs/0560-integer-overflow.html). It goes over a lot of this in depth, with a focus on overflow.

> But here what bothers me is that the operation doesn't fail because of an overflow / underflow or something else like this, but because it allows operations that may make no sense at all. I don't know if I'm clear?

Yes, right, this is what I tried to acknowledge initially. That it is a different reason, but different doesn't automatically mean bad. Indeed, I believe it's actually a much milder thing, because the panic is going to happen not at a boundary condition (like overflow, which is less likely to be tested), but any time you use units bigger than hours. It doesn't matter what the unit values are, you always get a panic.

This is why API design is hard. It's a balancing of trade offs. One path is indeed to remove the impls. But another path would be to, for example, define a new duration type that only supports hours or less. And then you could use that. And indeed, that exists! If you do `Timestamp + SignedDuration` or `Timestamp + std::time::Duration`, then those will only panic on overflow, since you can't get the units wrong.

This is really a problem with the intersection of a rich duration type like `Span` and a primitive timestamp type that doesn't know anything about calendars or time zones. On the one hand, it's convenient to make it work as well as can be, but on the other, just outright inhibiting `timestamp + 1.hour()` just because `timestamp + 1.day()` panics doesn't seem like the right trade off to me.

We can keep this issue open since I think there are some doc and error improvements to be made here. But I don't think these trait impls are going away. To be clear, I could be swayed on this point. But it's unlikely to come from first principles and rather empirical data that it's causing real bugs in real systems. Overflow can do that (but that's also true for integer arithmetic) and so can using the wrong units. But if you use the wrong units, then _any_ execution through that code path will panic immediately, and thus is very likely to be uncovered under even the lightest form of testing. That's an example of a _good_ panic IMO.

**Comment by ClementNerma** [comment]
I think it all comes down to personal preferences as well, I tend to prefer highly conservative APIs that explicitly requires checks (I wouldn't mind if the division operator disappeared completely to force users to use a dedicated fonction for numbers, or if the `array[index]` was removed entirely). Which is of course not everyone's cup of tea.

I will read the RFC you mentioned. Thank you very much for taking the time to answer with this much details :)

**Comment by BurntSushi** [comment]
Yeah that's definitely not my cup of tea. :-) But Jiff should offer fallible APIs for everything. So you should be able to get what you want with Jiff. (Just like with `std`.) It's less convenient, which is the [trade-off you pay by trying to avoid panicking branches](https://blog.burntsushi.net/unwrap/).

**Comment by mqudsi** [comment]
I ran into this myself; the conservative design of the library led me to assume that `ops::Sub` not returning a `Result<>` meant that the operation I was performing was safe.

**Comment by BurntSushi** [comment]
From #183:

> I'm a bit late to the jiff party and only started using it in anger this week, but I am wondering if you considering making `Sub::Output` a `Result<>` type instead (as a compromise between the current panicking behavior and removing `Sub` from `Timestamp` and co. altogether)?

I didn't consider this specifically, but I think this just falls into the same bucket: for better and worse, Jiff continues with `std`'s tradition here. My view is that if you're surprised by this, then you're likely also surprised by std's behavior on integer arithmetic. Either way, I prefer to be consistent with existing convention. If you're familiar with how to avoid std's panicking ops, then the same strategy will apply with Jiff.

**Comment by ClementNerma** [comment]
I feel like these are two different things. Overflow on basic arithmetic is one thing and you know you should just be aware of it. Whereas for a library you don't necessarily except panic overflow for small values.

**Comment by BurntSushi** [comment]
I don't see a practical difference between those things personally.

**Comment by mqudsi** [comment]
Fair enough, I can see where you are coming from. Rust could forcibly hold a developer’s hands by returning Result for operator arithmetic to the benefit of absolute newcomers (to a basic CS principle like addition overflow) and to the detriment of everyone that’s developed an intuition for when they might expect to run into an overflow/underflow scenario.

If your desire is to cater to people that have used jiff sufficiently to have developed such an intuition, then certainly no changes are needed. But the difference of course is that there are probably more devs keenly aware of when and where overflows can happen than those that realize that addition/subtraction of timestamps and “simple” durations might panic for reasons beyond overflow/underflow, namely being wary of calendar units larger than hours.

Personally, I think it’s only after delving into the documentation and issue discussions - and making mistakes along the way - that I finally have a handle on when I can expect jiff arithmetic operations that don’t involve arbitrary/user-provided values to panic.

(I do worry about “incidental” users of jiff: those that didn’t see its docs and choose this library but are interacting with one or more of its types because they’re exposed by another crate’s public api. Some crates don’t tend to get exposed by downstream crates but others, by nature of their purpose, do (see proliferation of chrono and time types in various crate public apis), though I’m not sure to what extent they’d be interacting with jiff, even if we’re talking basic add/sub operations.)

**Comment by BurntSushi** [comment]
I remain unconvinced. Some more points:

Even if the operators returned `Result`, users will likely _still_ be surprised by them failing when units greater than hours seep into their `Span` values. The only difference between that world and the status quo is how that failure manifests. It's unlikely that users will _want_ an error to occur when there are units of months or years. Instead, they'll want to change their approach or provide a relative datetime.

Additionally, the viewpoint represented here is not accounting for the viewpoint that would likely become much more prominent if I made all of the arithmetic operators fallible (or removed them). If they are fallible, then using them becomes much more annoying in cases where you don't care if they fail (or when you know they can't reasonably fail).

My viewpoint remains that it is a common and typical convention that Rust operators can and do fail for some subset of inputs.

The same intuition I personally have developed for broader Rust usage applies to Jiff equally well: if you want or need to avoid the possibility of panics, then you don't use the arithmetic (or indexing) operators and instead stick to explicit checked methods. This is a _API pattern of use_ that starts in `core` and Jiff continues it. It is my view that this is the least surprising thing. It is _not_ my view that _literally nobody_ will be surprised by it.

> If your desire is to cater to people that have used jiff sufficiently to have developed such an intuition, then certainly no changes are needed.

This is phrased in a way that basically makes it impossible to disagree with. The actual decision making procedure I use is to find a good _balance_. I don't work in absolutes and this style of argumentation won't be effective at changing my mind.

**Comment by mqudsi** [comment]
I’m actually not trying to change your mind or even personally convinced this *should* be changed - I’m just thinking aloud, so apologies if I came across strong. 

One thing in favor of keeping the status quo is that someone unaware of  cases that lead to panic won’t know what they don’t know: they could very realistically assume this is just a checked arithmetic operation to protect *only* against the conditions they know and expect (eg overflow/underflow) and might very well end up calling .unwrap() anyway.

**Comment by BurntSushi** [comment]
Fair enough. I appreciate you saying that.

> One thing in favor of keeping the status quo is that someone unaware of cases that lead to panic won’t know what they don’t know: they could very realistically assume this is just a checked arithmetic operation to protect only against the conditions they know and expect (eg overflow/underflow) and might very well end up calling .unwrap() anyway.

Plausibly, yes. While I'm a proponent of saying "unwrap is okay," it is also true that some are too liberal with its use.

**Comment by ClementNerma** [comment]
> Even if the operators returned Result, users will likely still be surprised by them failing when units greater than hours seep into their Span values. 

Actually this is a very good argument in favor of keeping things as they are. It's true that returning a `Result` may lead to the incorrect assumption that the operator would fail only in the case of arithmetic overflow, instead of >24h time span. So that makes a lot of sense.
