### ISSUE TITLE
provide `core`-only mode (i.e., `no-std` and `no-alloc`)

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/jiff#168]
From a [report on reddit](https://old.reddit.com/r/rust/comments/1hafdai/state_of_the_crates_2025/m1ntym0/):

-----

Of course, thank you for taking the time to reply! 

In an embedded context, there are lots of times where you need to work with Date/Time. For example, parsing messages that contain timestamps, scheduling events, or working directly with Time/Date providers like a GNSS (GPS) engine or NTP. 

On one of the devices we create at work provides logging capabilities with time stamped entries, and we fetch time via an NTP request. We also allow the user to adjust this time to account for their timezone. This requires us to work with timestamps using (currently) Chrono, but it's not always the easiest to work with. 

We also commonly work with GNSS engines which provide time in awkward formats like time since epoch, or directly as UTC, which is where a crate like yours would be great. 

IOT and Low-power devices used for home automation need to work with timestamps to schedule events, by converting this into a hardware timer to trigger the event or wake-up from low power mode.

Commonly libraries that are `no-std` and no `alloc` feature gate any formatting or string output, because string is heap allocated, but with crates like `heapless` and `defmt` used everywhere in embedded it would be helpful to be able to write into fixed size buffers instead.

I understand not wanting to bump MSVR, it's always difficult to balance keeping up with the ecosystem whilst maintaining support for those on older versions. Unfortunately embedded is quickly gaining traction and features are being added in the latest version to support this, so we are usually chasing the newest rust version!

**Comment by BurntSushi** [comment]
When I initially started building Jiff, it was my original intention to provide a `core`-only mode. (This is why Jiff has an `alloc` feature, although it cannot be disabled right now.)

One reason why I abandoned that goal was because it was much harder to devise a useful and chain-able `Error` type without dynamic memory allocation. But in theory, I could probably arrange it so that it just provides degraded error messages in a `core`-only context.

Another thing that seems to be mentioned above is time zone support. Currently, Jiff requires `std` to offer any kind of time zone support (whether it's by querying the system time zone or querying the time zone database). In theory, we could provide time zone support via bundling TZif data via `jiff-tzdb`. But things like the internal `Tzif` type store time zone transitions in a `Vec`. I suppose this is one advantage to the `chrono-tz` style of doing things: everything is built into statically known structures.

Another thing is that `jiff::tz::db()` returns a "singleton" database via a `OnceLock`. So we'd had to do something different there for `no_std` (which currently just always returns an empty time zone database).

And types like `TimeZoneDatabase`, and more crucially, `TimeZone` itself, both use an `Arc` internally to make cloning cheap. How to deal with that in a no-alloc context is less clear.

I'd say core-only support looks pretty challenging at this point, but not impossible.

**Comment by dickermoshe** [comment]
Are there any plans to add a `defmt` feature?

**Comment by BurntSushi** [comment]
I don't think I have any specific plans to do that myself soon since my focus is on Jiff 1.0 and I don't think adding `defmt` support is a backwards incompatible change. But I'd be open to reviewing a patch for it. It would need to be opt-in though.

**Comment by dickermoshe** [comment]
I started working on a PR and I quickly noticed that it would be rather
difficult to shoe in defmt for many structs (e.g. Error).

Would you be open to a PR that only implements it for the core structs?
(Zoned, Timestamp, etc) This would be sufficient for the vast majority of
use cases.

**Comment by BurntSushi** [comment]
Can you open a new issue instead of bumping an old one to talk about this? I would like to know what difficulties you're hitting and what the trade-offs are. I had been thinking of only providing impls for types that implement Display. Doing it for every type that implements Debug is likely overkill.

**Comment by BurntSushi** [comment]
I am generally okay with incremental progress. But I would like difficulties flagged in case there is something I should be doing for Jiff 1.0.

**Comment by dickermoshe** [comment]
I spent a couple of hours working on this today. At this point, defmt works with all public-facing structs and enums in jiff. However, it does not currently work when either the `std` feature or the `alloc` feature is enabled. (This is because `defmt` only implements on Format trait on `alloc::core::Box<T>` where `T` is `Sized`)

There is some value in making `defmt` compatible with alloc, but the lack of support should not be a blocker for now as most embedded devices do not have an allocator.

One important caveat: Supporting defmt comes with the trade-off that, if you ever want to take on a third-party dependancy for jiff, you will need to the upstream dependency to support defmt, or will need to create wrapper structs. I do see that you depend on very few third party dependencies, so this may not be an issue.

I’m still verifying that we don’t rely on `core::fmt` anywhere. The entire value proposition of `defmt` is to reduce compile-time code size and defer formatting until logs are rendered on a debugger. If any part of the code still uses `core::fmt` at runtime, that benefit is lost, and we are wasting out time.

---

btw, thanks for getting back to me so quickly, I cannot say how refreshing that is.
Thank you so much for this library!

**Comment by BurntSushi** [comment]
Please open a new issue

**Comment by BurntSushi** [comment]
@dickermoshe OK, with hands on a keyboard, I opened https://github.com/BurntSushi/jiff/issues/505 to talk about this.

In the future, please just open new issues instead of bumping old closed issues. Otherwise it's likely to get lost.

**Comment by dickermoshe** [comment]
I apologize. Thank you for opening a new issue.
