### ISSUE TITLE
Rename `Span` to `TimeSpan`?

### ISSUE THREAD

**Issue by rmg-x** [BurntSushi/jiff#31]
Personally, coming from the .NET/C# ecosystem, `Span` represents a contiguous memory region and `TimeSpan` represents a span of time.

Jiff's own documentation starts by mentioning the type as a "span of time represented via a mixture of calendar and clock units" 

Just a nitpick, but I think a rename would make more sense.

**Comment by BurntSushi** [comment]
A "span" is a very generic term, and I think it applies well here. It's true that some ecosystems use it to mean things like "contiguous memory," but Rust doesn't. For example, C enums and Rust enums are _very_ different. While I am sure that is the source of _some_ confusion, I don't think it's a Big Deal.

I would have used `Duration` (like Temporal), but that name is taken by `std::time::Duration`. And I like `Span` because it is very short _and_ matches common English vernacular. "Long span of time," for example, is pretty common phrasing.

**Comment by 8573** [comment]
`jiff` specifically deals with time, so `jiff::Span` is unambiguously a time span. I agree that `Span` alone, outside the context of `jiff`, is ambiguous, but one needn't refer to it ambiguously as `Span`.

**Comment by BurntSushi** [comment]
I am going to keep `Span`.
