### ISSUE TITLE
should unsigned integer types be used whenever possible?

### ISSUE THREAD

**Issue by AntoniosBarotsis** [BurntSushi/jiff#35]
A lot of the [`Zoned`](https://docs.rs/jiff/latest/jiff/struct.Zoned.html) return types for stuff like day/month etc are set to `i8/i16`s. 

I was curious what the rationale was for not choosing unsigned ints instead. 

I see that [internally](https://github.com/BurntSushi/jiff/blob/08dfdde204c739e38147faf70b648e2d417d1c2e/src/util/rangeint.rs#L2172-L2176) you make sure nothing is out of range anyway but wouldn't this also work with unsigned ints as well? Is there any point where you would want anything to be below zero?

**Comment by BurntSushi** [comment]
There are some values which can never be negative, like months. But there are some values which can be negative, like years. And any units on a `Span` can be negative too. (Well, the sign in that case is the property of the entire `Span`, but a negative span assigns a negative sign to each of its units when you inspect it.)

This implies that to be maximally descriptive, signed units should be used in some places while unsigned units should be used in others. I considered this, but I found it to be too annoying to deal with in practice. I found it simpler to just use signed integers everywhere. Moreover, the use of primitive integers like `i8` for the day are already making illegal values representable, even aside from the sign. For example, `120` is a valid `i8` but never a valid day. So using unsigned integers doesn't confer much advantage in my view because it doesn't actually shrink the size of representable but illegal values. It just shifts it around.

I also considered just returning `i64` for all units, even when an `i8` was big enough. Just for the sake of using the same integer type everywhere. But I thought that might be a bridge too far.

I'm open to changing my mind on this point, but I think it would require showing practical problems that folks run into as a result of using signed integers instead of unsigned integers wherever possible.

**Comment by AntoniosBarotsis** [comment]
Thanks a lot for the explanation! The `span` argument alone justifies this imo, I've never had to use something similar so I didn't even consider that. I think that using the smallest numeric type possible makes sense (as in I also wouldn't use `i64`s everywhere.

This is good to close from my end but I'm not sure if you want to leave it open for potential discussion by others so I'll leave the closing to you 😅

**Comment by BurntSushi** [comment]
OK, I'm going to close this out. If others have another perspective, please feel free to ask to re-open.
