### ISSUE TITLE
Benchmark improvements

### ISSUE THREAD

**Issue by jhpratt** [BurntSushi/jiff#38]
Some things that I noticed while looking through the benchmarks:

- Why `assert_eq!` on everything? Wouldn't `let _ = black_box(foo);` be sufficient for the compiler?
- Related to the previous, there's no need to calculate the Unix timestamp when checking for equality for either `chrono` or `time`. The values can be compared directly, avoiding an unrelated computation.
- `parse_civil_datetime` can use the well-known ISO 8601 format for `time`, which should be significantly faster. Otherwise it's using the same parsing mechanism as your `strptime` test.

**Comment by BurntSushi** [comment]
> Why assert_eq! on everything? Wouldn't let _ = black_box(foo); be sufficient for the compiler?

My philosophy on benchmarks is that they should have some kind of verification step that ensures they are arriving to the expected answer. I've been burned way too many times by benchmarks measuring something you don't expect because the result isn't checked.

> Related to the previous, there's no need to calculate the Unix timestamp when checking for equality for either chrono or time. The values can be compared directly, avoiding an unrelated computation.

There is one benchmark where this is intentional (`offset_to_instant`), and I'll rename that to `offset_to_timestamp` to better reflect the intent of the measurement. But you're right, the other benchmarks where I'm asking for a Unix timestamp from Chrono and `time` are wrong. I'll fix those. Likely a copy & paste related casualty.

> parse_civil_datetime can use the well-known ISO 8601 format for time, which should be significantly faster. Otherwise it's using the same parsing mechanism as your strptime test.

Oh nice catch! Yes, I'll fix this.

**Comment by jhpratt** [comment]
Yeah, I was referring to the benchmarks where it wasn't the intent. I recognized that one was specifically for that.
