### ISSUE TITLE
Span: Ergonomics Improvements 

### ISSUE THREAD

**Issue by martintmk** [BurntSushi/jiff#40]
First, let me say that I love the library. It just makes sense and the APIs are great to work with. Here are my thoughts after playing with the `Span` type:

**Easy conversion into the `Duration` type:**

It's a very common for service to get a span by subtracting timestamps. For example, by parsing retry-after header and applying sleep operation. Usually, sleep operation works with `Duration` and ti would be nice to have a built-in support for converting `Span` into `Duration`:

``` rust
let span = 1.minute();
let duration: Duration = span.try_into().unwrap();
assert_eq!(duration, Duration::from_secs(60));
```

**Check whether the Span is positive**

Currently, there is `is_zero` and `is_negative` APIs on the Span, I miss the `is_positive` method that tells me the `Span` contains som non-zero positive value. Usage would be:

``` rust
let diff = timestamp_2 - timestamp_1;

if diff.is_positive() {
    thread::sleep(diff.try_into());
} 
```

I was also missing `saturating_add` and `saturating_sub`, but that's covered by #10.

**Comment by BurntSushi** [comment]
For `Duration`, I think that's #21. Although it's important to note that spans with units greater than days _require_ a reference date. So you won't be able to just call `Duration::try_from(span)` because it doesn't have enough information. With that said, we could _provide_ a `TryFrom<Span> for Duration` that just fails if it has any units above days. I'm not 100% certain that's an OK API to add, but I think it probably seems fine.

One approach that can be done today is to feed the output of `Span::total` into [`Duration::try_from_secs_f64`](https://doc.rust-lang.org/std/time/struct.Duration.html#method.try_from_secs_f64). That will work even with calendar units since `Span::total` requires a reference date for spans with non-zero units greater than days.

Now, going from `Duration` to `Span` is much easier. That's just `Span::new().seconds().nanoseconds()`.

I'm definitely fine with adding `is_positive`.

**Comment by BurntSushi** [comment]
See: https://github.com/BurntSushi/jiff/issues/21#issuecomment-2251691543
