### ISSUE TITLE
Parsing continuous date values

### ISSUE THREAD

**Issue by cabbagestone** [BurntSushi/jiff#62]
I'm not sure if this is intended behavior, but when I try to do something like `%Y%m%d` with strptime (in my case, for a filename) it considers the whole value as a year, and of course, it's invalid.

here's an example:

```rust
let _ = Zoned::strptime("%Y%m%d-%H%M%S%z", "20240730-005625-0000").unwrap();
```

```
called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Adhoc(strptime parsing failed), cause: Some(Error { inner: ErrorInner { kind: Adhoc(%Y failed), cause: Some(Error { inner: ErrorInner { kind: Adhoc(year number is invalid), cause: Some(Error { inner: ErrorInner { kind: Range(RangeError(Negative { what: "year", given: 20240730, min: -9999, max: 9999 })), cause: None } }) } }) } }) } }
```

or

```rust
let _ = Zoned::strptime("%H%M%S%z", "005625-0000").unwrap();
```

```
called `Result::unwrap()` on an `Err` value: Error { inner: ErrorInner { kind: Adhoc(strptime parsing failed), cause: Some(Error { inner: ErrorInner { kind: Adhoc(%H failed), cause: Some(Error { inner: ErrorInner { kind: Adhoc(hour number is invalid), cause: Some(Error { inner: ErrorInner { kind: Range(RangeError(Negative { what: "hour", given: 5625, min: 0, max: 23 })), cause: None } }) } }) } }) } }
```

I was hoping to avoid separators in my filenames, but it's not mission-critical to omit them.

is there a separate way the library would support this sort of format? It's predictable and contained enough in my use case that I could just manually handle it as well.

**Comment by cabbagestone** [comment]
I've just read this in the docs about requiring separators:

https://docs.rs/jiff/latest/jiff/fmt/strtime/index.html#advice

I think it's worth noting that contiguous date values are common in filenames, but I'm happy to handle this situation in other ways.

anyways, closing because of the statement that the parsing is unlikely to change in the docs linked above.

**Comment by BurntSushi** [comment]
This is actually called out in the docs as a limitation. :-) https://docs.rs/jiff/latest/jiff/fmt/strtime/index.html#advice

For your specific format, if you wanted to omit separators, I'd suggest just using a regex. `regex-lite` would work nicely if you're dependency conscious and don't mind slower matching. With that said, it is unfortunately a mouthful:

```rust
use std::sync::LazyLock;

use anyhow::Context;
use jiff::{civil, tz::Offset, Zoned};
use regex::Regex;

fn main() -> anyhow::Result<()> {
    let name = "20240730-005625+0400";
    let zdt = parse_datetime_from_name(name)?;
    println!("{zdt}");

    Ok(())
}

fn parse_datetime_from_name(name: &str) -> anyhow::Result<Zoned> {
    static RE: LazyLock<Regex> = LazyLock::new(|| {
        Regex::new(
            r"(?x)
            ([0-9]{4})([0-9]{2})([0-9]{2})
            -
            ([0-9]{2})([0-9]{2})([0-9]{2})
            ([-+])
            ([0-9]{2})([0-9]{2})
        ",
        )
        .unwrap()
    });
    let Some(caps) = RE.captures(name) else {
        anyhow::bail!("{name} does not match format")
    };
    let (_, [year, month, day, hour, min, sec, sign, offh, offm]) =
        caps.extract();

    let year: i16 = year.parse().context("invalid year")?;
    let month: i8 = month.parse().context("invalid month")?;
    let day: i8 = day.parse().context("invalid day")?;
    let date = civil::Date::new(year, month, day).context("invalid date")?;

    let hour: i8 = hour.parse().context("invalid hour")?;
    let min: i8 = min.parse().context("invalid minute")?;
    let sec: i8 = sec.parse().context("invalid second")?;
    let time = civil::Time::new(hour, min, sec, 0).context("invalid time")?;

    let offh: i8 = offh.parse().context("invalid offset hours")?;
    let offm: i8 = offm.parse().context("invalid offset minutes")?;
    let off_seconds = i32::from(offh) * 60 * 60 + i32::from(offm) * 60;
    let mut off =
        Offset::from_seconds(off_seconds).context("TZ offset out of range")?;
    if sign == "-" {
        off = off.negate();
    }
    let tz = off.to_time_zone();

    date.to_datetime(time).to_zoned(tz).context("invalid datetime")
}
```

With that said, it seems like both Chrono's and Python's `strptime` is fine with your specific use case. I don't see how to make it work other than assuming the years, months and days never have more than two non-zero digits after the last leading zero digit. The only real downside here is that it would forever prevent parsing years greater than `9999`. Jiff already doesn't support years past `9999`. I'm hoping I never need to relax that, but if I do, it would imply `%Y` couldn't parse those years.

That actually seems like a fine trade-off to me. Because I agree, it would be nice to use `strptime` for your use case, and the alternative with regex is quite gnarly.

So I'm going to re-open this! Thank you for the issue.

**Comment by BurntSushi** [comment]
I guess the other downside is if you were representing years before `1000`. Then how would `9990101` parse? Apparently, ambiguously:

```
>>> datetime.datetime.strptime('9990730-005625', '%Y%m%d-%H%M%S')
datetime.datetime(9990, 7, 30, 0, 56, 25)
```

Chrono returns an error in this case.

So I don't know, it's definitely a little precarious. But workable. At least, I think, the rule I described above won't lead to any additional negatives, but will lead to strictly more formats being parseable.

Probably having delimiters is more robust unless you use a regex of some sort. `strptime` is definitely not growing regex like capabilities. :-)

**Comment by BurntSushi** [comment]
Your original example should now work in `jiff 0.1.4` on crates.io.

I'm really glad you missed the note in the docs at first and filed this issue. I think this is a big usability win. Because I've seen the kind non-delimiter format you're using in quite a few places over the years. Supporting it I think is a good idea.

I managed to sidestep the potential backcompat issue in the future by making parsing aware of padding. So if, for example, we expand the year range of Jiff beyond `-9999..=9999`, then one _can_ format and parse 5 digit years with `%5Y`, for example. Not especially ideal, but I'm happy as long as the path exists.

**Comment by cabbagestone** [comment]
Awesome, thank you very much for the fix, this makes my personal use-case significantly cleaner. I appreciate your methodical thinking process!
