### ISSUE TITLE
Should benchmarks be run on "random" values instead of the same value each time?

### ISSUE THREAD

**Issue by nakedible** [BurntSushi/jiff#80]
Currently the benchmarks in this library use hardcoded values to compare the performance of different functions in different libraries. This obviously produces pretty consistent benchmarks.

However, this is a bit problematic, as many algorithms actually spend a different amount of time depending on the value – for example, leap years are more expensive to calculate, month lengths affect calculations, leap days are very rare etc. Some values are fast to convert while others are slower. In addition to that, there's the problem of branch prediction – if the code in question uses branches, and it is evaluated always on the same value, the branch prediction will hit 100% correct. This means that the benchmarks are not really indicative of real world performance, nor are they good for comparing different implementations because one value might be fast in one implementation and slow in another.

The way to avoid this is to use a lot of different values to calculate the benchmarks and average them for the result. The easiest way to do this is by generating random values for the benchmarks. I personally use `iter_custom` with Criterion with the following implementation:

```rust
pub fn bencher<I: Copy, O>(s: impl Fn() -> I, f: impl Fn(I) -> O) -> impl Fn(u64) -> Duration {
    const ARR_SIZE: usize = 4096;
    move |n| {
        fastrand::seed(7);
        let is: [I; ARR_SIZE] = std::array::from_fn(|_| s());
        let now = Instant::now();
        for i in 0..n {
            let _ = black_box(f(is[i as usize & (ARR_SIZE - 1)]));
        }
        now.elapsed()
    }
}
```

This prepopulates a 4096 element array with random values always generated from the same seed, and then runs the function to be tested in a round robin fashion on the array. 4096 is big enough so there will be a couple leap days in there as well, but usually not so big that memory performance becomes an issue. 

What do you think, would this be worthwhile for this library as well? Would you want a pull request converting the benchmarks to use random values instead with the method shown above?

**Comment by BurntSushi** [comment]
I think it's probably fine to add this style of benchmark (as long as the seed is fixed) as _additional_ benchmarks, but the existing benchmarks on fixed inputs should 100% stay. I am open to changing the values of the fixed inputs, but I would generally prefer for them to be representative. I'm not sure if they're perfect on that dimension today though.

More generally though, I'm not totally convinced by your suggested solution. I think a better answer is probably to have a better benchmark harness that uses [random interleaving](https://github.com/google/benchmark/issues/1051). The problem with your suggested approach, IMO, is that it's much harder to reason about the path through the code because its taking an aggregate result. The aggregate result will likely yield more realistic _wall clock timings_, but I think they are less useful from the perspective of profiling hot spots, looking at generated code and trying to do targeted optimizations. So that in turn leads me to a place where we probably want both, and not just one.

I will say though that my bandwidth is limited and this sort of tuning in the benchmarks isn't really my priority right now. I'm open to a PR, but depending on its size/complexity, it could be a while before I can review it.

**Comment by BurntSushi** [comment]
I'm going to close this for now since I don't have any specific plans to pursue this at present. I'd be open to accepting a PR with this style of benchmark added to the existing benchmarks though. (But not replacing them.)
