### ISSUE TITLE
Zoned supports now_with_time_zone

### ISSUE THREAD

**Issue by 1996fanrui** [BurntSushi/jiff#93]
Currently, Zoned has now funcation to return the current system time in this system's time zone. Could we introduce the now_with_time_zone for Zoned?

It's needed for some reasons:

1. How to create a now Zoned with specific time zone for current code?

    ```rust
    // solution 1
    Zoned::new(Timestamp::now(), time_zone)
    
    // Solution 2, logforth[1] is using this solution.
    Zoned::now().with_time_zone(tz)
    ```

    `Zoned::now` (Solution2) has clearer semantics for developers, but it requires repeated creation of TimeZone objects. (Zoned::now needs to clone a default TimeZone, and with_time_zone also requires a TimeZone).

    I have a benchmark for them[2]:
        - The avg time solution 1 is 297.61 ns
        - The avg time solution 2 is 443.87 ns
        - 297.61 ns * 151% = 443.87 ns, so performance of solution 1 is totally better than solution. 

2. The ZonedDateTime[3] of Java has 3 now functions, it includes now(), now(ZoneId) and now(Clock). It's useful for developers.

[1] https://github.com/fast/logforth/blob/b2d5e7e664595f58d35377136b4936fc4ac22c3f/src/layout/text.rs#L89
[2] https://github.com/1996fanrui/fanrui-learning/blob/aacfa73de1a2299745241806f61aa098d0b66a23/rust-learning/benches/jiff_benchmark.rs#L6
[3] https://docs.oracle.com/en%2Fjava%2Fjavase%2F11%2Fdocs%2Fapi%2F%2F/java.base/java/time/ZonedDateTime.html#now(java.time.ZoneId)

**Comment by BurntSushi** [comment]
OK, so this issue you opened has a basically identical description in the PR, which makes it confusing to me where to talk about this. But I guess I'll discuss API design here.

I think one solution you missed here is `Timestamp::now().to_zoned(time_zone)`. Which I would somewhat prefer here since I do find `Zoned::now_with_time_zone` to be a somewhat unwieldy name. I tried hard to avoid a bunch of "now with foo" constructors in Jiff's API and instead preferred composition of existing APIs instead.

**Comment by BurntSushi** [comment]
I will say that it is pretty unfortunate that `Zoned::now().with_time_zone(time_zone)` is that much slower. So another path here is to get these into micro-benchmarks and see if that can be improved. I suppose it's not possible to solution 2 exactly as fast as solution 1, because solution 2 does need to call `TimeZone::system()`. Now that _should_ be very quick in the vast majority of cases since it's cached. So I do expect some difference, but the difference you report is pretty big. So it would be good to understand the root cause of that.

**Comment by 1996fanrui** [comment]
> I think one solution you missed here is Timestamp::now().to_zoned(time_zone). Which I would somewhat prefer here since I do find Zoned::now_with_time_zone to be a somewhat unwieldy name. 

I really think the function name is a little long, do you have any suggestion?

This function is easy to be found for developers. They want to use Zoned directly, they don't know Timestamp have a good function.

That's why I propose introduce a function for Zoned.

**Comment by 1996fanrui** [comment]
> I will say that it is pretty unfortunate that Zoned::now().with_time_zone(time_zone) is that much slower. So another path here is to get these into micro-benchmarks and see if that can be improved.

I could file a PR to add it to benchmark tomorrow. And I'm happy to look into it how to improve the performance.

**Comment by BurntSushi** [comment]
I agree that an alternative constructor can increase discoverability. But I don't know how far I want to go down that road. Adding this routine is also likely to provoke a desire for, e.g., `Zoned::new_with_iana` as well, to mirror `Zoned::now().intz("US/Central")` or whatever.

One middle ground here, that would I think address your discoverability concerns, is to add a note to the `Zoned::now` docs mentioning `Timestamp::now().to_zoned(TimeZone::UTC)` as an alternative. But the problem I have with that is the docs would specifically need to call out that the only reason to do such a thing would be to avoid the superfluous fetching of the system time zone. It's a bit subtle.

Yes, I think the next step here is to do a perf investigation.

**Comment by 1996fanrui** [comment]
Hey @BurntSushi , I have a question during analyzing the performance. Why does the cache of system default time zone need expiration?

The time zone can be changed, right? For example, the Mac or mobile phone is moved from region A to region B.

[1] https://github.com/BurntSushi/jiff/blob/c659069a2765a5e28ba503ea37e8a2eee4b10a92/src/tz/system/mod.rs#L79
