### ISSUE TITLE
proposal: Timestamp.elapsed()

### ISSUE THREAD

**Issue by dvdsk** [BurntSushi/jiff#98]
We have since which is pretty great but gets a bit long:
```rust
Timestamp::now().since(end).expect("Span can represent the difference between any two possible timestamps").get_seconds() > 5
```

I propose a method analogous to the std such that the above becomes:
```rust
end.elapsed().get_seconds() > 5
```

**Comment by BurntSushi** [comment]
I think I'm open to this, but one thing to consider here is that `since` accepts a [`TimestampDifference`](https://docs.rs/jiff/latest/jiff/struct.TimestampDifference.html, which provides a way to specify balance/round settings on the span produced. With the API proposed here, there is no parameter on `elapsed()` and thus no way to specify those settings. And arguably, adding that parameter would somewhat defeat the motivation of adding this in the first place.

Moreover, #86 is adding `duration_since` APIs to all datetime types, including `Timestamp`, which returns a `SignedDuration`. Maybe that's what `Timestamp::elapsed` should return? Otherwise there would probably need to be `Timestamp::elapsed` (for `Span`) and `Timestamp::duration_elapsed` (for `SignedDuration`). Which is kind of a bummer.

Finally, should this method be added to `Zoned` as well? I think so, yes.

What about the civil datetime types? I think the answer to that is "no," because they don't have `now()` constructors (and they shouldn't have them).

**Comment by BurntSushi** [comment]
One nice thing here is that since Jiff uses signed durations/spans, this won't need to return an error. (Although it can panic in the same cases that `Timestamp::now()` can panic.)

**Comment by dvdsk** [comment]
>  adding that parameter would somewhat defeat the motivation of adding this in the first place.

agreed, but does the time-difference parameter make sense in the context of elapsed? 

I no nothing of the internals of jiff, and I appreciate the complexity of handling time correctly so all I am going on is this bit in the docs: 

> Example: available via subtraction operator
> 
> This routine can be used via the - operator. Since the default configuration is used and because a Span can represent the difference between any two possible timestamps, it will never panic.

from: [example-available-via-subtraction-operator](https://docs.rs/jiff/latest/jiff/struct.Timestamp.html#example-available-via-subtraction-operator-1)

Adding an `elapsed` will allow `Timestamp` to be used like a portable version of std's `Instant`. As long as the default configuration returns a span with nanosecond resolution that seems safe to me.

>returns a `SignedDuration`. Maybe that's what Timestamp::elapsed should return?

I do not think negative duration's make sense with `elapsed`. If the timestamp is in the future then zero seconds have elapsed, not negative some number. Instead of saturating it could return an `Option` (which you could then `unwrap_or_default()` to get saturating again). The same however could be said about `since`.

> Finally, should this method be added to Zoned as well? I think so, yes.
> 
> What about the civil datetime types? I think the answer to that is "no," because they don't have now() constructors (and they shouldn't have them).

I have no idea, for a timestamp its simple, for a `Zoned` more complex. I think it could become a foot-gun with the current `Zoned::now()` API. But I am biased there, since I think the current `Zoned::now` API might be a footgun.

**Comment by BurntSushi** [comment]
> Adding an elapsed will allow `Timestamp` to be used like a portable version of std's `Instant`. 

Nooooooooooooooo. A `Timestamp` is like std's `SystemTime`. A `std::time::Instant` is something else entirely. It's _monotonic_ time.

> agreed, but does the time-difference parameter make sense in the context of elapsed?

Oh for sure it does. It makes sense in exactly the same way it makes sense for `Timestamp::now().since(end)`.

> I do not think negative duration's make sense with elapsed. If the timestamp is in the future then zero seconds have elapsed, not negative some number. Instead of saturating it could return an Option (which you could then unwrap_or_default() to get saturating again). The same however could be said about since.

The question here is whether it should be a `Span` or a `SignedDuration`. Both are signed. And yes, `elapsed()` should be able to return a negative duration, just like any other method in Jiff that can return a negative duration. I don't think `elapsed()` should be a special case here.

> I have no idea, for a timestamp its simple, for a Zoned more complex. I think it could become a foot-gun with the current Zoned::now() API.

I don't see why. It's just as simple for `Zoned`.

> But I am biased there, since I think the current `Zoned::now` API might be a footgun.
>
> Off-topic: is the Zoned::now() API open for discussion (in another issue)?

Yes, please open a new issue.

Popping up a level, I interpreted this issue as "`Timestamp::now().since(time).unwrap().get_seconds()` is a mouthful, can we have a shorter way of writing the same thing?" And indeed, `time.elapsed().get_seconds()` is one such way. And if it's the same thing, then `elapsed()` just looks like this:

```rust
fn elapsed(self) -> Span {
    Timestamp::now().since(self).unwrap()
}
```

Like that's it. But it seems like from your response here that you actually think `elapsed()` should _not_ be equivalent to `Timestamp::now().since(time).unwrap().get_seconds()` and should be something else entirely.

And there is still the question of what duration type to return. I actually lean more towards a `SignedDuration` over a `Span`, but I'm not sure. And I really don't want `elapsed()` and `duration_elapsed()` methods.

**Comment by dvdsk** [comment]
> But it seems like from your response here that you actually think `elapsed()` should _not_ be equivalent to `Timestamp::now().since(time).unwrap().get_seconds()` and should be something else entirely.

I'll be honest I thought so too but the negative duration and elapsed is nagging me. But yes it makes no sense for it to be different then `Timestamp::now().since()`.

>  Nooooooooooooooo. A Timestamp is like std's SystemTime. A std::time::Instant is something else entirely. It's monotonic time.

Ahh yes thats on me I had those the wrong way round.

**Comment by BurntSushi** [comment]
I think the calculus may have changed somewhat here with the addition of `SignedDuration`. Now, instead of this:

```rust
Timestamp::now().since(start).expect("Span can represent the difference between any two possible timestamps").get_seconds() > 5
```

You can write:

```
Timestamp::now().duration_since(start).as_secs() > 5
```

I'm inclined to pass on a new `elapsed()` API in favor of asking users to write the above. The above is pretty succinct and easy to read I think. It is also correct. By avoiding `elapsed()`, we side-step the question of which duration type to return, and if we did return `Span`, how to specify the extra options found on `Timestamp::since`.

**Comment by dvdsk** [comment]
I am still in favor of adding elapsed, simply for readability. Its more specific in communicating the intend in my opinion. Regarding the type, given the current api it seems logical to mirror those:

```rust
Timestamp::now().duration_since(start)
``` 
motivates an elapsed api used like this: 
```rust
start.elapsed_duration()
```
---------
```rust
Timestamp::now().since(start).expect("Span can represent the difference between any two possible timestamps")
```
motivates an elapsed api used like this: 
```rust
start.elapsed()
```

I think letting `elapsed` just return a `Span` instead of  `Result<Span, Error>` works right?

**Comment by BurntSushi** [comment]
> A downside of such an approach is that there are now two elapsed functions to add to each time type

The only time types it makes sense to add `elapsed` to is `Timestamp` and `Zoned`.

> Am I right that that is the tradeoff? Keeping number of members a reasonable length vs the readability benefits of elapsed?

That's part of it. I also have a suspicion that folks using this method will want a `SignedDuration` in most cases, which the naming scheme makes more verbose. And if we have a `Span` variant, then it also has no easy way of accepting the same kinds of options as `since` does. (I mentioned this earlier.)

So this is not just about a "number of methods." There's a question of uncertainty in my mind where the naming scheme you propose would actually end up making the more common case more verbose. 

> Its more specific in communicating the intend in my opinion. 

I agree, but I think the benefit over the current status quo is extremely small now. If was bigger before support for `SignedDuration` landed. That's why I'm leaning towards rejecting this: there are some costs, some uncertainty and the benefit is small.

**Comment by BurntSushi** [comment]
OK, after giving this more thought, I think I'm going to reject this request for now. In addition to what I said above, I think a method called `elapsed` imbues a strong connotation of monotonic time that would be very inappropriate for a system clock time like `Timestamp`. I think it just does a little bit too much nudging in the wrong direction in an area that is already rather subtle and confusing. Moreover, the cost of the status quo seems pretty small IMO.
